plugins {
        id 'net.fabricmc.fabric-.gradle`**:
Certifique-se de que o `settings.gradle` tenha o bloco de repositório do Fabric:

```groovy
pluginManagement {
    repositories {
        maven {
            loom' version '1.17.10'
        id 'maven-publish'
}
name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
    }
}

rootProject.name = 'MMY'
